references:
  envoy-build-image: &envoy-build-image
  envoyproxy/envoy-build-ubuntu:e7ea4e81bbd5028abb9d3a2f2c0afe063d9b62c0

version: 2
jobs:
  build:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh build
  test:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh test

workflows:
  version: 2
  all:
    jobs:
      - build
      - test
